# Generated by Django 6.0.5 on 2026-05-16 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do EPI')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('ca', models.CharField(blank=True, max_length=50, verbose_name='Certificado de Aprovação (CA)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(verbose_name='Data de Entrega')),
                ('data_prevista_devolucao', models.DateTimeField(verbose_name='Previsão de Devolução')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('status', models.CharField(choices=[('Emprestado', 'Emprestado'), ('Fornecido', 'Fornecido'), ('Devolvido', 'Devolvido'), ('Danificado', 'Danificado'), ('Perdido', 'Perdido')], default='Emprestado', max_length=20, verbose_name='Status')),
                ('observacao_devolucao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.colaborador', verbose_name='Colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.equipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
